run:
  timeout: 30s  

linters:
  enable:
    - errcheck
    - gochecknoglobals
    - gochecknoinits
    - gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unparam
    - unused
