name: main

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
          fetch-depth: '0'
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.20.0"
      - name: Test Script
        run: ./test.sh
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.55.0
        env:
          WITH_V: true
          DRY_RUN: true
      - name: Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.18.0
        with:
          skip-version-file: true
          skip-commit: true
          output-file: false
          skip-tag: true
          release-count: 1
      - name: Print Changelog
        env:
          CHANGELOG: ${{ steps.changelog.outputs.clean_changelog }}
        run: echo $CHANGELOG
  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.55.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - name: Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.18.0
        with:
          skip-version-file: true
          skip-commit: true
          output-file: false
          skip-tag: true
          release-count: 1
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
